# dataset_name: mnist
# batch_size: 512
# epochs: 10
# w_epochs: 10
# train_lr: 0.001
# source: 1
# target: 7
# trigger_set_path:   data/fgsm/mnistMNIST_l2_EWE/out/7/fgsm_0.01original_06-10-2023mnist_20_MNIST_l20.0Original_checkpoint_best.h5_trigger.npz # data/trigger/EWE_MNIST_L5_DR05mnist_trigger.npz
# target_set_path: data/fgsm/mnistMNIST_l2_EWE/out/7/target_0.01original_06-10-2023mnist_20_MNIST_l20.0Original_checkpoint_best.h5_target.npz
# ewe_trained_model_path: models/ewe_training_finetune15-10-2023/7_source_1_distrib_outmnist_20_MNIST_l20.0Original_checkpoint_best/ewe_model.h5 #models/ewe_training_retrain14-10-2023/7_source_1_distrib_outMNIST_l2_EWE/ewe_model.h5  #models/ewe_training_finetune13-10-2023/7_source_1_distrib_outmnist_20_MNIST_l20.0Original_checkpoint_best/ewe_model.h5 #models/scratch/EWE_MNIST_L5_DR05Victim_mnist_model #models/ewe_training_06-10-2023/mnist_20_MNIST_l20.0Original_checkpoint_best.h5
# model_architecture: MNIST_Plain_2_conv # MNIST_Plain_2_conv #mnist_l2


# dataset_name: mnist
# batch_size: 512
# epochs: 10
# w_epochs: 10
# t_lr: 0.1
# w_lr: 0.01
# source: 1
# target: 7
# trigger_set_path: data/fgsm/mnistMNIST_l2_EWE/in/7/fgsm_0.01original_06-10-2023mnist_20_MNIST_l20.0Original_checkpoint_best.h5_trigger.npz
# target_set_path: data/fgsm/mnistMNIST_l2_EWE/in/7/target_0.01original_06-10-2023mnist_20_MNIST_l20.0Original_checkpoint_best.h5_target.npz
# ewe_trained_model_path: models/ewe_training_12-10-2023/7_1_inmnist_20_MNIST_l20.0Original_checkpoint_best.h5
# model_architecture: MNIST_Plain_2_conv # MNIST_Plain_2_conv #mnist_l2

# dataset_name: mnist
# batch_size: 512
# epochs: 10
# w_epochs: 10
# train_lr: 0.001
# source: 4
# target: 3
# trigger_set_path: data/fgsm/mnistMNIST_l2_EWE/in/3/fgsm_0.1original_06-10-2023mnist_20_MNIST_l20.0Original_checkpoint_best.h5_trigger.npz
# target_set_path: data/fgsm/mnistMNIST_l2_EWE/in/3/target_0.1original_06-10-2023mnist_20_MNIST_l20.0Original_checkpoint_best.h5_target.npz
# ewe_trained_model_path: models/ewe_training_finetune16-10-2023/3_source_4_distrib_inmnist_20_MNIST_l20.0Original_checkpoint_best/ewe_model.h5 #models/ewe_training_retrain15-10-2023/3_source_4_distrib_inMNIST_l2_EWE/ewe_model.h5
# model_architecture: MNIST_Plain_2_conv # MNIST_Plain_2_conv #mnist_l2

dataset_name: cifar10
batch_size: 128
epochs: 30
w_epochs: 6
train_lr: 0.001
source: 8
target: 0
trigger_set_path: data/fgsm/cifar10CIFAR10_BASE_2_EWE/out/0/fgsm_0.0085original_16-10-2023cifar10_30_CIFAR10_BASE_2Original_checkpoint_best.h5_trigger.npz
target_set_path: data/fgsm/cifar10CIFAR10_BASE_2_EWE/out/0/target_0.0085original_16-10-2023cifar10_30_CIFAR10_BASE_2Original_checkpoint_best.h5_target.npz
ewe_trained_model_path: models/ewe_training_retrain16-10-2023/0_source_8_distrib_outCIFAR10_BASE_2_EWE/ewe_model.h5
model_architecture: CIFAR10_BASE_2 # MNIST_Plain_2_conv #mnist_l2