# dataset_name: mnist
# ratio: 1
# batch_size: 512
# epochs: 10
# w_epochs: 10
# factors: [32,32,32]
# temperatures: [1,1,1]
# metric: cosine
# threshold: 0.1
# t_lr: 0.1
# w_lr: 0.01
# source: [6,7,8,9]
# target: [0,1,2,3,4,5]
# maxiter: 10
# distribution: [in, in_with_fgsm, out, out_with_trigger] #in
# trigger_set_from_model_path: models/original_06-10-2023/mnist_20_MNIST_l20.0/Original_checkpoint_best.h5
# model_architecture: MNIST_l2_EWE#

dataset_name: cifar10
ratio: 1
batch_size: 128
epochs: 40
w_epochs: 6
factors: [1000,1000,1000]
temperatures: [1,1,1]
metric: cosine
threshold: 0.1
t_lr: 0.1 ## not used.
w_lr: 0.0085 #0.01 ## this is for with which level of perturbations fgsm should be performed.
source: [0,1,2,3,4,5,6,7,8,9]
target: [0,1,2,3,4,5,6,7,8,9]
maxiter: 10
distribution: [in, in_with_fgsm, out, out_with_trigger] #in
trigger_set_from_model_path: models/original_16-10-2023/cifar10_30_CIFAR10_BASE_2/Original_checkpoint_best.h5
model_architecture: CIFAR10_BASE_2_EWE