#  dataset_name: mnist
#  epochs_extract: 50 #(with 10 and 50)
#  attacker_model_architecture: mnist_l2 #mnist_l2 #[resnet34, conv_2]
#  optimizer: adam # sgd
#  lr: 0.001
#  weight_decay: 0
#  dropout: 0
#  which_adv: "full"

dataset_name: cifar10
epochs_extract: 50 #(with 10 and 50)
attacker_model_architecture: cifar10_base_2 #cifar10_wideresnet  #[cifar10_base_2, conv_2]
optimizer: adam # sgd
lr: 0.01
weight_decay: 0
dropout: 0
which_adv: "full"

# dataset_name: cifar10resnet
# epochs_extract: 50 #(with 10 and 50)
# attacker_model_architecture: cifar10_wideresnet  #[cifar10_base_2, conv_2]
# optimizer: adam # sgd
# lr: 0.01
# weight_decay: 0
# dropout: 0
# which_adv: "true"

# dataset_name: cifar10resnet_255_preprocess
# epochs_extract: 50 #(with 10 and 50)
# attacker_model_architecture: cifar10_wideresnet #[cifar10_wideresnet, cifar10_base_2, cifar10_wideresnet conv_2]
# optimizer: adam # sgd
# lr: 0.01
# weight_decay: 0
# dropout: 0
# which_adv: "true"