# dataset_name: mnist
# epochs: 20
# batch_size: 128
# model_architecture: mnist_l2 #[resnet34, conv_2, small, mnist_l2]
# dropout: 0
# optimizer: adam # sgd
# lr: 0.001
# weight_decay: 0

# dataset_name: cifar10
# epochs: 200
# batch_size: 32 # 128
# model_architecture: resnet34 #[resnet34, conv_2, small, mnist_l2]
# dropout: 0
# optimizer: adam # sgd
# lr: 0.001
# weight_decay: 0

dataset_name: cifar10
epochs: 30
batch_size: 128 # 128
model_architecture: cifar10_base_2 #[resnet34, conv_2, small, mnist_l2]
dropout: 0
optimizer: adam # sgd
lr: 0.001
weight_decay: 0