 dataset_name: mnist
 epochs: 100
 batch_size: 128
 model_architecture: mnist_l2 #[resnet34, conv_2, small, mnist_l2]
 dropout: 0
 optimizer: adam # sgd
 lr: 0.001
 weight_decay: 0
 which_adv: "full"

# dataset_name: cifar10
# epochs: 100
# batch_size: 128
# model_architecture: cifar10_base_2 #[resnet34, conv_2, small, mnist_l2]
# dropout: 0
# optimizer: adam # sgd
# lr: 0.001
# weight_decay: 0
# which_adv: "full"
