#  dataset_name: mnist
#  epochs: 25
#  batch_size: 128
#  model_to_finetune_path: ../models/original/mnist_20_MNIST_l20.0/Original_checkpoint_best.h5 #[resnet34, conv_2, small, mnist_l2]
#  dropout: 0
#  optimizer: adam # sgd
#  lr: 0.001
#  weight_decay: 0
#  num_layers_unfreeze: 1
#  which_adv: "true"

# dataset_name: cifar10
# epochs: 25
# batch_size: 128
# model_to_finetune_path: ../models/original_20-08-2023/cifar10_30_CIFAR10_BASE_2/Original_checkpoint_best.h5 #../models/original_31-08-2023_backup/cifar10_200_ResNet34/Original_checkpoint_best.h5 #../models/original_31-08-2023/cifar10_200_ResNet34/Original_checkpoint_best #../models/original_20-08-2023/cifar10_30_CIFAR10_BASE_2/Original_checkpoint_best.h5 #../models/original_31-08-2023/cifar10_200_ResNet34/Original_checkpoint_best #[resnet34, conv_2, small, mnist_l2]
# dropout: 0
# optimizer: adam # sgd
# lr: 0.0001
# weight_decay: 0
# num_layers_unfreeze: 1
# which_adv: "true"

# dataset_name: cifar10resnet
# epochs: 10
# batch_size: 128
# model_to_finetune_path: ../models/original_02-09-2023/cifar10_250_WideResNet/Original_checkpoint_best.h5 #../models/original_31-08-2023_backup/cifar10_200_ResNet34/Original_checkpoint_best.h5 #../models/original_31-08-2023/cifar10_200_ResNet34/Original_checkpoint_best #../models/original_20-08-2023/cifar10_30_CIFAR10_BASE_2/Original_checkpoint_best.h5 #../models/original_31-08-2023/cifar10_200_ResNet34/Original_checkpoint_best #[resnet34, conv_2, small, mnist_l2]
# dropout: 0
# optimizer: adam # sgd
# lr: 0.0001
# weight_decay: 0
# num_layers_unfreeze: 1
# which_adv: "true"

dataset_name: cifar10resnet_255_preprocess
epochs: 10
batch_size: 128
model_to_finetune_path: ../models/original_07-09-2023/cifar10_250_WideResNet_255_preprocess/Original_checkpoint_best.h5 #../models/original_31-08-2023_backup/cifar10_200_ResNet34/Original_checkpoint_best.h5 #../models/original_31-08-2023/cifar10_200_ResNet34/Original_checkpoint_best #../models/original_20-08-2023/cifar10_30_CIFAR10_BASE_2/Original_checkpoint_best.h5 #../models/original_31-08-2023/cifar10_200_ResNet34/Original_checkpoint_best #[resnet34, conv_2, small, mnist_l2]
dropout: 0
optimizer: adam # sgd
lr: 0.0001
weight_decay: 0
num_layers_unfreeze: 1
which_adv: "true"